name: 'Publish Labspace'
description: 'Packages the project as a tarball and publishes it as a Labspace using Docker Compose'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  target_repo:
    description: 'The repo where the Compose file should be published'
    required: true
  target_tag:
    description: 'The tag of the published Compose file'
    required: false
    default: 'latest'
  labspace_base_version:
    description: 'The version of the base Labspace Compose file'
    required: false
    default: 'latest'
  labspace_override_files:
    description: 'Path to Labspace-specific Compose override files, comma-separated'
    required: false
    default: '.labspace/compose.override.yaml'
  

runs:
  using: 'composite'
  steps:
    - name: Setup Docker Compose
      uses: docker/setup-compose-action@v1
      with:
        version: v2.39.3

    - name: Set contentVersion in Labspace metadata
      shell: bash
      run: |
        if [ ! -f labspace.yaml ]; then
          echo "Error: labspace.yaml not found in repository root"
          exit 1
        fi
        CONTENT_VERSION=$(git rev-parse --short HEAD)
        echo "Setting contentVersion in labspace.yaml to $CONTENT_VERSION"
        
        if grep -qE '^[[:space:]]*contentVersion:' labspace.yaml; then
          # Use portable in-place edit across GNU/macOS sed
          sed -i.bak "s/^\([[:space:]]*contentVersion:\).*/\1 $CONTENT_VERSION/" labspace.yaml && rm -f labspace.yaml.bak
        else
          echo "Warning: contentVersion: not found in labspace.yaml; skipping update"
        fi

    - name: Create project tarball and encode
      shell: bash
      run: |
        echo "Creating tarball of project..."
        tar -czf /tmp/project.tar.gz \
          --exclude='.git' \
          --exclude='node_modules' \
          --exclude='.github/workflows/*labspace*' \
          --exclude='project.tar.gz' \
          .

        echo "Base64 encoding tarball..."
        # Use portable base64 invocation (GNU/macOS)
        base64 /tmp/project.tar.gz > /tmp/project.tar.base64

        echo "Tarball created and encoded successfully"

    - name: Generate compose overrides with embedded tarball
      shell: bash
      run: |
        echo "Generating .labspace/compose.pipeline.yaml..."
        mkdir -p .labspace

        # Create the pipeline compose file
        cat > .labspace/compose.pipeline.yaml << 'EOF'
        configs:
          project_source_tar:
            content: |
        EOF

        # Append the base64 content with proper indentation
        cat /tmp/project.tar.base64 | sed 's/^/      /' >> .labspace/compose.pipeline.yaml

        # Append the service configuration to mount the config and specify its location
        cat >> .labspace/compose.pipeline.yaml << 'EOF'

        services:
          configurator:
            configs:
              - source: project_source_tar
                target: /etc/labspace-support/content.tar.base64
            environment:
              PROJECT_TAR_PATH: /etc/labspace-support/content.tar.base64
        EOF

        echo "Compose pipeline file generated successfully"

    - name: Publish to Labspace
      shell: bash
      run: |
        echo "Publishing Labspace..."

        OVERRIDES_FLAG=""
        IFS=',' read -ra OVERRIDE_FILES <<< "${{ inputs.labspace_override_files }}"
        for override_file in "${OVERRIDE_FILES[@]}"; do
          override_file=$(echo "$override_file" | xargs)  # trim whitespace
          if [ -f "$override_file" ] || [[ "$override_file" == "oci://"* ]]; then
            OVERRIDES_FLAG="$OVERRIDES_FLAG -f $override_file"
          else
            echo "Overrides file '$override_file' not found; skipping."
          fi
        done

        docker compose \
          -f oci://dockersamples/labspace:${{ inputs.labspace_base_version }} \
          ${OVERRIDES_FLAG} \
          -f .labspace/compose.pipeline.yaml \
          publish ${{ inputs.target_repo }}:${{ inputs.target_tag }} --with-env -y

        echo "Labspace published successfully"
